---
# tasks file for setup_nginx
- name: Printing tad_s content
  ansible.builtin.debug:
    var: tads_test_flag1

- name: Adding a pause
  ansible.builtin.pause:
    seconds: 15
    
- name: Checking nginx service
  ansible.builtin.shell:
    cmd: systemctl status nginx
  register: checking_nginx_service_details
  ignore_errors: yes

- name: Not found nginx scenario, tasks execution
  block:
    - name: yum update
      ansible.builtin.shell: yum update -y
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      register: nginx_installation_details
  when: checking_nginx_service_details.failed

- name: Checking nginx service status prompt
  ansible.builtin.debug:
    msg: "Nginx is already installed in the system"
  when: not checking_nginx_service_details.failed

- name: Post installation steps tasks execution
  block:
    - name: Copy nginx config to /etc/nginx/conf.d
      ansible.builtin.copy:
        src: "employee_app_nginx.conf"
        dest: /etc/nginx/conf.d

    - name: Restart the nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Allow the firewall the 8080 port
      ansible.builtin.shell:
        cmd: firewall-cmd --add-port=8080/tcp --permanent

    - name: Disable the SELinux for the server (stackoverflow suggestion https://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx)
      ansible.builtin.shell:
        cmd: setsebool -P httpd_can_network_connect 1

  when: not nginx_installation_details.failed | default(True)
