---
- name: Playbook for appserver setup
  hosts: appservers
  become: yes

  tasks:
    - name: Install docker
      import_role:
        name: install_docker

    - name: Setup mysql
      import_role:
        name: setup_mysql

- name: Playbook for webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Setup Nginx
      import_role:
        name: setup_nginx