---
# - name: Playbook for appserver setup
#   hosts: appservers
#   become: yes

#   tasks:
#     - name: Install docker
#       ansible.builtin.import_role:
#         name: hms.aap_sample_app_deployment.install_docker

#     - name: Setup mysql
#       ansible.builtin.import_role:
#         name: hms.aap_sample_app_deployment.setup_mysql

# - name: Playbook for webserver setup
#   hosts: webservers
#   become: yes
#   tasks:
#     - name: Setup Nginx
#       ansible.builtin.import_role:
#         name: hms.aap_sample_app_deployment.setup_nginx

- name: Playbook for webserver setup
  hosts: webservers
  become: yes
  vars_files:
    - __vars/common_vars.yml
  collections: 
    - hms.aap_sample_app_deployment
  roles:
    - setup_nginx