- name: Playbook for uninstall docker
  hosts: appservers
  become: yes
  vars_files:
    - ../__vars/common_vars.yml
  collections: 
    - hms.aap_sample_app_deployment
  roles:
    - uninstall_docker